<?php

namespace Site\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfileRepository extends EntityRepository
{
}
