site_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SiteUserBundle:Default:index }
    
SiteUserBundle_user:
    resource: "@SiteUserBundle/Resources/config/routing/user.yml"
    prefix:   /user

SiteUserBundle_userprofile:
    resource: "@SiteUserBundle/Resources/config/routing/userprofile.yml"
    prefix:   /userprofile