parameters:
#    site_user.example.class: Site\Bundle\UserBundle\Example

services:
#    site_user.example:
#        class: %site_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
